### ISSUE TITLE
Compile command

### ISSUE THREAD

**Issue by peq** [wurstscript/wurst4vscode#2]
Add a command to compile the project to Jass.

**Comment by Frotty** [comment]
Is this something different from run/buildmap?

**Comment by peq** [comment]
Sometimes you might want to compile without the map. Otherwise this is already covered now and can be closed.

**Comment by Cokemonkey11** [comment]
I think this could even cover injecting into a map file, just not running it in wc3.

Consider a wurst dev environment on linux without wine, maybe?

**Comment by Frotty** [comment]
> I think this could even cover injecting into a map file

difference to buildmap?

> Consider a wurst dev environment on linux without wine, maybe?

wine is only needed for pjass. disable pjass and you don't need wine. already works
