### ISSUE TITLE
Update setup explanation

### ISSUE THREAD

**Issue by Frotty** [wurstscript/wurst4vscode#26]
https://marketplace.visualstudio.com/items?itemName=peterzeller.wurst

This still shows an old, deprecated way of setting wurst up. 
It should link to https://wurstscript.github.io/start.html instead

**Comment by peq** [comment]
The setup tool only adds a configuration to the project, right? So it is not the correct way to setup the plugin itself, just to setup a project.

I think, we should change the plugin, so that it includes the setup tool and downloads the compiler itself.

**Comment by Frotty** [comment]
Yes, and in the linked page, at the bottom, you explain how to do the config that the wurstplugin needs, which the setup does?

Packaging the setup tool sounds good, however how will it be run when the plugin is only executed after a .wurst file has been opened (which should be generated by the plugin)?

In that sense the setup should be run at any startup or in regular intervals to check if the dependencies are uptodate.

**Comment by Frotty** [comment]
Please still already link to the new project setup now.
