### ISSUE TITLE
about keyword Intelligent prompt

### ISSUE THREAD

**Issue by zhongying1995** [wurstscript/wurst4vscode#27]
```
对于关键字，能否智能提示？当我写 ext 时，编译器会提示 extends？例如，我写下imple时，会出现implements。而且，插件对很多关键字都不进行提示，是我没开启？还是编译器本身没有做这个功能？
```
i hold when i code down ext ,the phugin will prompt extends;
eg: imple  ==> implements
and,so mang keywords can not be prompt,likes function ,class ...
is the reason i have no turn on this function,or is the phugin do not have this function?

this is Chinglish.....en, i hold you know what i told about

**Comment by Frotty** [comment]
It doesn't have that function.

**Comment by zhongying1995** [comment]
how should i use the syntax [  #define  HELLO  "hello" (in jass) ];
maybe,i should [ constant HELLO = “hello”(in wurst) ]？？？？
 i found it in the manual,but cannot find it.

**Comment by Frotty** [comment]
Please use markdown formating.

```
constant HELLO = "hello"
```
This will have a similar effect to define, yes.
Please also don't put multiple issues/simple questions in a ticket, they aren't really ment for that.
Feel free to visit our irc channel if you need some general answers to basic questions: https://webchat.quakenet.org/?channels=#inwc.de-maps

**Comment by peq** [comment]
Keywords are now suggested by autocomplete (https://github.com/wurstscript/WurstScript/commit/16b531e7bc9de41b8962008c2a9f0d745bec9b87)
