### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by luciouskami** [wurstscript/wurst4vscode#28]
when i created a new map with wurst,and tpye  and run,it shows "Internal error, please look at the server's logs.".But I don't know where is the log..But I use the example map,no error shows

Here is the map:
[map2.zip](https://github.com/wurstscript/wurst4vscode/files/1759625/map2.zip)

**Comment by Frotty** [comment]
You can find the logs at `~\.wurst`
Where `~` is your user's home directory.
e.g. `C:\Users\Frotty\` on windows.

**Comment by luciouskami** [comment]
Here is the log.
[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/1759645/languageServer.log)

**Comment by Frotty** [comment]
Your map is corrupt - It misses some files/entries. 
When I save the map in World Editor, it works fine afterwards.
It's either protected, or relies on the resource pack files in the game directory.

**Comment by luciouskami** [comment]
ok, I will rebuild the map
