### ISSUE TITLE
runmap error

### ISSUE THREAD

**Issue by SteelDuos** [wurstscript/wurst4vscode#29]
Hello, this is my first experience using wurst and I got some troubles with runmap/build for the map: "
Command 'wurst: Run a Wurst map' resulted in an error." This map is empty and created by wurst installer, I changed nothing. Warcraft is on version 1.26a.

![image](https://user-images.githubusercontent.com/37386561/37435766-bcf43f62-27f5-11e8-9125-2aedd322b9f1.png)

**Comment by Frotty** [comment]
Please post the log from `~\.wurst\logs`

**Comment by SteelDuos** [comment]
[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/1815819/languageServer.log)
[setup.log](https://github.com/wurstscript/wurst4vscode/files/1815820/setup.log)

Compiler file is empty.

**Comment by Frotty** [comment]
Can't see anything obvious except that there is no runmap command registered at all.
Are you sure you have waited for the workspace initialization and selected the map properly?
You shouldn't manually edit settings, if that's what you did.

Do you get errors if you edit the Hello.wurst package to create one?

The other thing it could be are Cyrillic letters and spaces in the filenames.
Need more info 🤔

**Comment by SteelDuos** [comment]
> Are you sure you have waited for the workspace initialization and selected the map properly?
I think yes.
> You shouldn't manually edit settings, if that's what you did.
No, it is clear new map.
> The other thing it could be are Cyrillic letters and spaces in the filenames.
I thought about this and fixed some names, but error is still there.

> Need more info
What kind of info? I will try to give all I can.

**Comment by Frotty** [comment]
> No, it is clear new map.
I was taking about vscode and wurst config, which you have opened in the screenshot

> What kind of info? I will try to give all I can.
How we can reproduce it. As I said, the runmap call isn't even in the log like it should be.
Try to close vscode, delete the languageServer.log, then open vscode and try to run map. After error, copy and paste the new log here.

**Comment by SteelDuos** [comment]
[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/1816748/languageServer.log)

"I was taking about vscode and wurst config, which you have opened in the screenshot"
I only tried to change language to English, but this error was even before.

"You also didn't answer whether you get compile errors"
As I understood there are no any other compiler errors, only this small window in the corner.

My sequence of actions was that:
1) Patching java
2) Installing vs and wurst plugin
3) Installing wurst.jar and creating new clear project.
4) Then I opened wurst.build and chose workspace. After I tried to type >runmap and got this error.

After I tried to change all cyrillic names and reinstalled all things, but nothing changed.

**Comment by Frotty** [comment]
Well, again, there is no runmap entry in the log and your paths still contain spaces/Cyrillic characters from your username.
So the error happens before the runmap command is even sent to the language server it seems.
When you execute runmap, do you get the file selection to select the map to run? This:
![](https://i.imgur.com/SnAoUAx.png)
compiler.log still empty?

**Comment by Frotty** [comment]
any update here?
