### ISSUE TITLE
docComments  better support 

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/wurst4vscode#31]
just like 
/**
 *
 */
func(....)
now it is work on vscode but i have to write the /**  *  *   */ 
can we support it like on the eclipse
easy to get this:
/** aa
 * @param unit u
 * @return int
 */
function   aa(unit u) returns int
.......

**Comment by Frotty** [comment]
We do not plan to add parameter behavior or html, but the description should be parsed by vscode as markdown iirc.

**Comment by PhoenixZeng** [comment]
yes it worked 
but now i should enter this particular format
it is to boring to write the " * " and " / "  When we are familiar with the use of some IDE
when we want write a comment on eclipse we just should write "/" + "**" and down the "enter" key.
can we have the same action on the vscode?

**Comment by peq** [comment]
Maybe this is possible with snippets: https://code.visualstudio.com/docs/editor/userdefinedsnippets

I'll have a look.
