### ISSUE TITLE
ExecuteFunc problem in Legacy Map war3map.j

### ISSUE THREAD

**Issue by yatyricky** [wurstscript/wurst4vscode#32]
Generated war3map.j through
```
.\clijasshelper.exe ..\temp\common.j ..\temp\blizzard.j "path\to\my\map.w3x"
```

raises syntax error
```
[Wurst] Wurst does only support ExecuteFunc with a single string as argument.
```

at

```
function Command___execfuncs takes string str returns nothing
    call ExecuteFunc(SubString(str, 5, StringLength(str)))
endfunction
```

# Environment

- Windows 10 Pro 1709
- Warcraft 3 1.28.5
- Wurst build 628
- J2SE: 1.8.0_162
- VS Code Extension: peterzeller.wurst-0.1.13
- Map file: https://github.com/yatyricky/Zulaman-WE/blob/master/ZAM%20ruins%20WIP.w3x

# What did I do

1. Install wurst by WurstSetup.jar
2. Create Project
3. Open from VS Code
4. Install extension
5. Build MyWurstProject: success 👍 
6. Run ExampleMap.w3x: success 👍 
7. Extract war3map.j from my vJass map
8. Replace MyWurstProject\wurst\war3map.j with generated jass
9. Add -noExtractMapScript in wurst_run.args
10. Replace mod/step/print with mod_nowurst and step_nowurst and print_nowurst because they are keywords
11. Syntax error on ExecuteFunc 👎 

![tim20180402103449](https://user-images.githubusercontent.com/2650631/38181134-c0ebd96e-3663-11e8-9e15-a7bdafd7bbe1.png)

# The porject

https://www.dropbox.com/s/zetu2m21lbj2o5z/MyWurstProject.zip?dl=0

**Comment by Frotty** [comment]
That's not a problem, it's a limitation.
Wurst simply doesn't allow using non-constant strings in ExecuteFunc because names aren't stable. So you need to implement that functionality otherwise.

Thanks for the detailed report though.
