### ISSUE TITLE
runmap doesnt work

### ISSUE THREAD

**Issue by freddyalready** [wurstscript/wurst4vscode#34]
When I try to execute the runmap command, i get the following error message.
![error runmap](https://user-images.githubusercontent.com/38360937/38775801-4cd8c9ba-408b-11e8-878c-ea754210ccc3.PNG)

Note that the buildmap command works perfectly fine. Thanks for your help!

Here are the log files:

[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/1911748/languageServer.log)
[setup.log](https://github.com/wurstscript/wurst4vscode/files/1911749/setup.log)
[compiler.log](https://github.com/wurstscript/wurst4vscode/files/1911750/compiler.log)

Edit: When I execute runmap, i dont get the dropdown menu where i should select the map.

**Comment by Frotty** [comment]
Hi.
Then what do you get instead of the map dropdown? Instantly the error?
There is no log related to runmap being executed in your logs.
Did you set your gamepath correctly when creating the project using the setup tool?

**Comment by freddyalready** [comment]
Hey,
I set up the gamepath to my warcraft 3 folder (where the Warcraft III.exe is located)

**Comment by freddyalready** [comment]
And I get instantly the error message.

**Comment by freddyalready** [comment]
Could it be a problem that the .wurst folder is on another partition than my warcraft 3 folder? The paths are
C:\Users\Frederic\.wurst\
and
D:\Spiele\Warcraft3\Warcraft3\

**Comment by Frotty** [comment]
possibly.
Need to find some log with a trace about the error. The logs you posted don't contain any. Maybe check output tabs in vscode.

**Comment by freddyalready** [comment]
i dont get any outputs in vscode, but i looked through the wurst extention files and found the commands.ts file. I think the runmap command should be in there right?

[out_features_commands.txt](https://github.com/wurstscript/wurst4vscode/files/1914164/out_features_commands.txt)

[src_features_commands.txt](https://github.com/wurstscript/wurst4vscode/files/1914163/src_features_commands.txt)

but it seems that there is no runmap command defined in those two files

**Comment by Frotty** [comment]
any progress?

**Comment by vitalexbel** [comment]
Hi!
@freddyalready you can delete file `Warcraft III\Maps\Test\WurstTestMap.w3x`
It solved the same problem for me

**Comment by freddyalready** [comment]
Awesome, that worked! Thank you very much!
