### ISSUE TITLE
Custom "Modify all occurences" command in the editor

### ISSUE THREAD

**Issue by RoOoBerT** [wurstscript/wurst4vscode#35]
Hello dear developers,

About the function "Modify all occurrences" (Right click on a token > CTRL + F2) in VS code with Wurst code :
At the moment, it seems that the only thing it does is search+replace in the whole file, without any form of intelligence. If you rename a variable "a" to "b", then it will literally replace all "a" in the current file with "b", which includes : comments, stbtic types, string literbls, etc.

That would be great to fix this function so it renames only references to the selected element (variable, local variable, function or type name).
I have not deeply tested it, but it seems like that the function "Find all references" (SHIFT + F12) works fine, maybe you can reuse code ?

Cheers !

**Comment by peq** [comment]
Implemented a first experimental version of the feature, reusing the "Find all references" feature as you suggested.

Probably needs more work to make it stable, so it would be nice if you could test it in practice.

Make sure you use the right shortcut: There is one command "Change All Occurrences" which works without language support and just does search/replace and there is another feature for "Rename Symbol", which uses the language support.

**Comment by RoOoBerT** [comment]
You wouldn't believe how frequently I (ab)use this function. So don't worry, I will test it intensely and keep you informed about the results.
Thanks for the effort and your rapidity ! :)

**Comment by RoOoBerT** [comment]
I tested a few times and at the moment the function "Rename symbol" seems to work fine. I renamed classes and variables without issue, that even renamed the corresponding files.

However, I don't know if this is linked, but **since today I cannot use 'runmap'.** VS Code shows "Internal error" message without additional information.
My log file shows no error, see : https://pastebin.com/bxCy0UyW
