### ISSUE TITLE
Run a Wurst map not working

### ISSUE THREAD

**Issue by eGlint** [wurstscript/wurst4vscode#38]
Hello! 

Since patch 1.29.2, whenever I use "Run a Wurst map" or "Run the last map again" in Visual Studio Code, it fails to open a test map. I think the problem is it is still using "War3.exe " instead of "Warcraft III.exe".

**Comment by Frotty** [comment]
Then delete your war3.exe. 1.29+ doesn't have that one anymore.

**Comment by eGlint** [comment]
It now works! Weird, I thought the patch already deleted War3.exe.  

Well, thank you very much!

**Comment by Frotty** [comment]
We will implement a mechanic to not select `war3.exe` with patch 1.29 to avoid future issues.
Thanks for the report.
