### ISSUE TITLE
Language client can't initialize

### ISSUE THREAD

**Issue by Trokkin** [wurstscript/wurst4vscode#39]
### Symptoms:
- Autocomplete doesn't work
- `Run a wurst map`/`Build your map via wurst.build` returns error `Language client is not ready yet`
- `Clean the Wurst workspace` returns error `command 'wurst.clean' not found`
- Every other command returns failure error
- [Language server log](https://bin.wurstlang.org/obihuvodef.wurst) shows language server is working.
### Diagnostics:
I've cloned repo, debugged extension and found this:
- this.state is struck at ClientState.Starting
- Promise from `connection.initialize(initParams)` (client.js:1716) is never fulfilled nor rejected because leading `.then()` callbacks are never called.
- Language server is running.

So we've got to conclusion that language client does not succeed with initialization/start.

OS is Linux Mint 18.2, VSCode version 1.24.1, wurstscript build 839
No idea on how to reproduce this bug.

**Comment by peq** [comment]
This is broken since https://github.com/wurstscript/WurstScript/commit/a84d720388eb36228d404b2c0a84d3bf8c135a69

@Frotty can you check what you broke there? :P

**Comment by Frotty** [comment]
I don't see any reason for it, and so far trokkin is the only one having issues, afaik.

**Comment by peq** [comment]
It's also failing on my machine, so probably something in the new library is Windows only.

**Comment by Frotty** [comment]
Most likely. @WaterKnight ?
