### ISSUE TITLE
Highlight occurences of variables

### ISSUE THREAD

**Issue by peq** [wurstscript/wurst4vscode#5]

**Comment by Frotty** [comment]
It's working but there are a few cases where it's applying highlight to wrong areas.
- Casing is ignored
- Selecting an int,real,string, the value will be highlighted even if it's just part of another int, real, string
![image](https://cloud.githubusercontent.com/assets/1486037/15981859/f0f81294-2f7b-11e6-83f5-9cc6d26b81a0.png)
- Selecting only part of a word, will highlight that part everywhere else
![image](https://cloud.githubusercontent.com/assets/1486037/15981868/22784316-2f7c-11e6-919b-393aa4d7f266.png)

**Comment by Frotty** [comment]
still needed!
