### ISSUE TITLE
There is no runmap command

### ISSUE THREAD

**Issue by Alexander-Alekseev** [wurstscript/wurst4vscode#52]
I did use Wurst one year ago and everything was okay. Today I wanted to install it again and I faced with the problem that there is no runmap command in VS Code.

![image](https://user-images.githubusercontent.com/32123066/59161609-b03a3e00-8aed-11e9-8bb0-0a58f35feaa6.png)

I have a clean installation literally of everything:
- Wurst (I installed and configured grill and then tried to create projects via both GUI and command line);
- Wurst project;
- Warcraft III v. 1.31;
- VS Code;
- "Wurst language support" plugin for VS Code.

My steps after creating a new project (as I mentioned above I tried both GUI and command line tools to create a new project):
- open VS Code;
- open folder with project;
- open Hello.wurst file;
- Ctrl+Shift+B;
- start typing "runmap" and ">runmap".

Logs attached.
[compiler.log](https://github.com/wurstscript/wurst4vscode/files/3269745/compiler.log)
[languageServer.log](https://github.com/wurstscript/wurst4vscode/files/3269746/languageServer.log)
[setup.log](https://github.com/wurstscript/wurst4vscode/files/3269747/setup.log)

**Comment by Frotty** [comment]
> Ctrl+Shift+B;

That's wrong, the commands are not build tasks. You need to hit F1 or whatever key you have bound to "Show All Commands".

**Comment by Alexander-Alekseev** [comment]
Ah, thanks!

**Comment by Frotty** [comment]
You're welcome!
If you enjoy wurst, consider leaving a star on our main repo https://github.com/wurstscript/WurstScript
Cheers 🍻
