### ISSUE TITLE
How can I turn off auto indentation executed by "Wurst language support" extension?

### ISSUE THREAD

**Issue by tester1101** [wurstscript/wurst4vscode#60]
**Describe the bug**
Unwanted indentation caused by VS extenstion "Wurst language support".

**To Reproduce**
Explained in Screenshots below.

**Expected behavior**
Explained in Screenshots below.

**Screenshots**

Expected behavior (case 1)>>
![copy_paste_extension_off](https://user-images.githubusercontent.com/57724590/144740186-db61c366-6b85-4333-a7a9-b5e4b4d06604.gif)

But in real (case 2) >>
![copy_paste_extension_on](https://user-images.githubusercontent.com/57724590/144740188-92db40d0-bb35-4a96-9489-85f9f36f9182.gif)

I wanted case1 but I get case2 when VS extenstion "Wurst language support"(WIS) is enabled.
I can get case1 when WIS is disabled.
So, I think WIS make unexpected indentation.

--
--
--
--
--
--

There are other cases like this.

##Write a new function between...
-when WIS disabled.
![newfunction_extension_off](https://user-images.githubusercontent.com/57724590/144748888-dcc2347c-87a7-4b8b-bb25-08144410f789.gif)

-when WIS enabled.
![newfunction_extension_on](https://user-images.githubusercontent.com/57724590/144749030-fa544b2d-e9b5-47b7-ac5e-6995a06f8aeb.gif)

Edit: I uploaded wrong gif!
--
--
--
--
--
--
##Write a new enum 
-when WIS disabled.
![newenum_extension_off](https://user-images.githubusercontent.com/57724590/144740190-a76ef5e8-d525-465f-80f8-0b9168932fe0.gif)

-when WIS enabled.
![newenum_extension_on](https://user-images.githubusercontent.com/57724590/144740191-f360bb40-de5f-47c3-8d89-09a9d5e0f56c.gif)

There may be more cases like this.

So what I have to do for disabling auto indentation in WIS?

Thank you.

**Desktop (please complete the following information):**
 - OS: Window
 - Browser : Firefox
 - Version : 8.1

**Comment by peq** [comment]
Vscode has an option called `Editor: Auto Indent` where you can disable the smart indentation.

I'll also check if we can make it work better. It seems a bit broken in your examples, so thanks for the report.

**Comment by peq** [comment]
Just changed the indentation configuration. Can you update to extension version 0.6.0 and try if this fixes your problems?

**Comment by tester1101** [comment]
No more problems, very nice! Thank you!
I haven't changed configuration, but updating extension may have worked.
